// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLJ8YrmEfO80g1y6xyBV-dvjemKjPzeVM',
    appId: '1:171017960924:web:9f4376e79ae0ad3cdaa319',
    messagingSenderId: '171017960924',
    projectId: 'kb-shop-d3216',
    authDomain: 'kb-shop-d3216.firebaseapp.com',
    storageBucket: 'kb-shop-d3216.appspot.com',
    measurementId: 'G-048TDF149S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClHxKi113FmbX2VLBH3XIbtZyO5RHIigc',
    appId: '1:171017960924:android:0d6690d2adbe9228daa319',
    messagingSenderId: '171017960924',
    projectId: 'kb-shop-d3216',
    storageBucket: 'kb-shop-d3216.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdRQ6vG5wTkSsTJFPNp2cMrki2Yqkix5Q',
    appId: '1:171017960924:ios:8af8f7f34cc4dfe4daa319',
    messagingSenderId: '171017960924',
    projectId: 'kb-shop-d3216',
    storageBucket: 'kb-shop-d3216.appspot.com',
    iosBundleId: 'com.example.kbShopAdmin',
  );
}
